'use strict';
window.TULPA_MCP_ONLY=true;
const $=id=>document.getElementById(id);
const state={ready:true,busy:false,loading:false,watchBusy:false};
const READ_FIELDS={qq_per_chat:'read-qq-per-chat',wechat_per_chat:'read-wechat-per-chat'};
let jobStarting=null,toastTimer,homeBusy=false;
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
async function watchApi(path,body,method){const r=await fetch(path,{method:method||(body===undefined?'GET':'POST'),cache:'no-store',headers:{'Content-Type':'application/json','X-ChatWeave-UI':'1'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw Error(d.detail||'请求未完成');return d;}
function syncControls(){syncDataControls(Boolean(state.loading||state.watchBusy||jobStarting));}
function readLimits(){return Object.fromEntries(Object.entries(READ_FIELDS).map(([key,id])=>[key,$(id).valueAsNumber]));}
function showReadLimits(){const valid=Object.values(READ_FIELDS).every(id=>!$('read-enable-'+id.split('-')[1]).checked||$('read-all-'+id.split('-')[1]).checked||$(id).validity.valid);$('read-window-summary').hidden=valid;$('read-window-summary').textContent=valid?'':'每会话条数上限须为 1–10000 之间的整数。';}
async function loadReadOptions(){const rules=await watchApi('/api/read-options');for(const [key,id]of Object.entries(READ_FIELDS)){const r=rules[key];$(id).min=r.min;$(id).max=r.max;$(id).value=r.default;}showReadLimits();}
async function monitorWatchJob(id){state.watchBusy=true;syncControls();try{while(true){const job=await watchApi('/api/watch-jobs/'+id);renderImportProgress(job);$('read-progress').hidden=false;$('read-progress').textContent=job.events.join('\n');if(job.status!=='running'){if(job.error)throw Error(job.error);$('read-progress').textContent+='\n'+(job.result?.summary||'处理完成');break;}await new Promise(r=>setTimeout(r,800));}}finally{state.watchBusy=false;syncControls();await refreshHome();}}
async function openData(){if(state.loading)return;if(!$('data-dialog').open)$('data-dialog').showModal();state.loading=true;syncControls();try{await loadDataSettings();await loadReadOptions();await loadSync();}catch(e){toast(e.message);}finally{state.loading=false;syncControls();}}
async function loadSync(){const s=await watchApi('/api/refresh-status');$('sync-summary').textContent=s.platforms.map(p=>(p.platform==='qq'?'QQ':'微信')+'：'+p.status+' '+(p.detail||'')).join('；');$('auto-refresh').value=s.auto_refresh.minutes;$('auto-refresh-stickers').checked=s.auto_refresh.load_stickers;const job=s.running_jobs?.[0];if(job&&!state.watchBusy)void monitorWatchJob(job.id).catch(e=>toast(e.message));}
async function refreshHome(){if(homeBusy)return;homeBusy=true;try{const [m,ops]=await Promise.all([watchApi('/api/mcp'),watchApi('/api/mcp/operations')]);$('lite-service').textContent=m.error||(m.running?'MCP 运行中 · '+m.url:'尚未开启 MCP，点击“连接 Agent”开始。');$('lite-data').textContent=Object.entries(m.data_platforms).map(([p,n])=>(p==='qq'?'QQ':'微信')+' '+n.toLocaleString()+' 条消息').join(' · ')||'暂无聊天资料，请先导入。';$('data-status').textContent=$('lite-data').textContent;const host=$('lite-operations');host.replaceChildren();for(const o of ops.operations.slice(0,20)){const card=document.createElement('article'),title=document.createElement('strong'),text=document.createElement('pre'),note=document.createElement('p');title.textContent=o.connection_name+' · '+({SUCCEEDED:'已完成',FAILED:'失败',UNKNOWN:'结果未知',EXECUTING:'执行中'}[o.state]||o.state);text.textContent=o.summary;note.textContent=new Date(o.created*1000).toLocaleString()+' · '+(o.result.note||'');card.append(title,text,note);host.append(card);}if(!ops.operations.length)host.textContent='暂无操作。';}catch(e){$('lite-error').textContent=e.message;}finally{homeBusy=false;}}
async function openOnebot(){try{const [s,p]=await Promise.all([watchApi('/api/desktop/status'),watchApi('/api/desktop/preferences')]);$('lite-onebot-url').value=s.settings.sender_url;$('lite-onebot-token').value='';$('lite-background').checked=p.background;$('lite-background-label').hidden=!s.owned;if(!$('lite-onebot').open)$('lite-onebot').showModal();}catch(e){toast(e.message);}}
async function testOnebot(){const r=await watchApi('/api/desktop/onebot/test',{});$('lite-onebot-result').textContent=r.message;}
$('open-data').onclick=$('home-import').onclick=openData;$('home-connect').onclick=()=>$('open-mcp').click();$('open-onebot').onclick=openOnebot;
window.addEventListener('tulpa-open-settings',openOnebot);
$('lite-onebot-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await watchApi('/api/desktop/settings',{sender_url:$('lite-onebot-url').value,sender_token:$('lite-onebot-token').value},'PUT');$('lite-onebot-token').value='';await testOnebot();}catch(e){$('lite-onebot-result').textContent=e.message;}finally{b.disabled=false;}};
$('lite-onebot-test').onclick=()=>testOnebot().catch(e=>toast(e.message));
$('lite-background').onchange=()=>watchApi('/api/desktop/preferences',{background:$('lite-background').checked,mode:'mcp'},'PUT').catch(e=>toast(e.message));
$('lite-onebot').addEventListener('close',()=>{$('lite-onebot-token').value='';});
for(const id of ['auto-refresh','auto-refresh-stickers'])$(id).onchange=()=>watchApi('/api/auto-refresh',{minutes:Number($('auto-refresh').value),load_stickers:$('auto-refresh-stickers').checked}).catch(e=>toast(e.message));
for(const p of ['qq','wechat'])$('reconnect-'+p).onclick=()=>watchApi('/api/sync/reconnect',{platform:p}).then(()=>toast('进度已重建，等待下一次读取')).catch(e=>toast(e.message));
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
// The MCP edition imports directly from clients; legacy file imports belong to the full app.
$('import-form').closest('details').hidden=true;
Object.values(READ_FIELDS).forEach(id=>$(id).oninput=showReadLimits);
setInterval(()=>{if(!document.hidden)void refreshHome();},4000);
function showVoiceComponent(s){const busy=['downloading','cancelling'].includes(s.status),ready=s.status==='installed';$('voice-component-status').textContent=s.message+(busy?' · '+(s.downloaded/1048576).toFixed(1)+' / '+(s.total/1048576).toFixed(1)+' MB':'');$('voice-component-progress').hidden=!busy;$('voice-component-progress').value=s.total?s.downloaded/s.total*100:0;$('voice-component-install').disabled=busy||ready;$('voice-component-install').textContent=ready?'已安装':'一键安装语音模型';$('voice-component-cancel').hidden=!busy;$('voice-component-cancel').disabled=s.status==='cancelling';}
async function refreshVoiceComponent(){try{showVoiceComponent(await watchApi('/api/components/voice'));}catch(e){$('voice-component-status').textContent=e.message;}}
for(const action of ['install','cancel'])$('voice-component-'+action).onclick=async()=>{try{showVoiceComponent(await watchApi('/api/components/voice',{action}));}catch(e){toast(e.message);}};
setInterval(()=>{if(!document.hidden)void refreshVoiceComponent();},2000);void refreshVoiceComponent();
Promise.resolve().then(async()=>{await loadReadOptions();await refreshHome();const d=await watchApi('/api/desktop/status');$('lite-version').textContent='Tulpa MCP '+d.version;const anchor=new URLSearchParams(location.search).get('anchor');if(anchor&&/^\d+$/.test(anchor))await openChat(Number(anchor));}).catch(e=>toast(e.message));
